define([
  "./config",
  "./Game",
  "./GameObject",
  "./Component",
  "./Camera",
  "./components/CameraComponent",
  "./components/TransformComponent",
  "./components/SpriteRenderer",
  "./lib/gl-matrix",
  "./components/PathRenderer",
  "./components/TextRenderer",
  "./primitives/Plane",
  "./primitives/Box",
  "./primitives/Cone",
  "./primitives/Ball",
  "./Canvas2dViewport",
  "./DirectionalLight",
], function (
  config,
  Game,
  GameObject,
  Component,
  Camera,
  CameraComponent,
  TransformComponent,
  SpriteRenderer,
  glMatrix,
  PathRenderer,
  TextRenderer,
  Plane,
  Box,
  Cone,
  Ball,
  Canvas2dViewport,
  DirectionalLight,
) {
  return (window.scaliaEngine = {
    config: config,
    Game: Game,
    GameObject: GameObject,
    Component: Component,
    Camera: Camera,
    CameraComponent: CameraComponent,
    TransformComponent: TransformComponent,
    SpriteRenderer: SpriteRenderer,
    glMatrix: glMatrix,
    PathRenderer: PathRenderer,
    TextRenderer: TextRenderer,
    Plane: Plane,
    Box: Box,
    Cone: Cone,
    Ball: Ball,
    DirectionalLight: DirectionalLight,
    Canvas2dViewport: Canvas2dViewport,
  });
});
